name: Promote Test To Main

on:
  push:
    branches:
      - test

permissions:
  contents: write

jobs:
  merge:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"

      - name: Merge test into main
        run: |
          git fetch origin
          git checkout main
          git merge origin/test --no-edit
          git push origin main

      - name: Notificar despliegue exitoso
        if: success()
        run: |
          curl -s -X POST \
          https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendMessage \
          -d chat_id=${{ secrets.TELEGRAM_CHAT_ID }} \
          -d text="🚀 Merge automático test → main realizado correctamente."

      - name: Notificar error en despliegue
        if: failure()
        run: |
          curl -s -X POST \
          https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendMessage \
          -d chat_id=${{ secrets.TELEGRAM_CHAT_ID }} \
          -d text="❌ Error durante el merge automático hacia producción."